package com.oo.spring.WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.7
 * 2013-05-09T17:47:34.782+08:00
 * Generated source version: 2.6.7
 * 
 */
@WebServiceClient(name = "HelloImpService", 
                  wsdlLocation = "http://localhost:8080/MyCXF/getHell?wsdl",
                  targetNamespace = "http://com.test") 
public class HelloImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.test", "HelloImpService");
    public final static QName Hello2ImpPort = new QName("http://com.test", "Hello2ImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/MyCXF/getHell?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/MyCXF/getHell?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "Hello2ImpPort")
    public IHello getHello2ImpPort() {
        return super.getPort(Hello2ImpPort, IHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "Hello2ImpPort")
    public IHello getHello2ImpPort(WebServiceFeature... features) {
        return super.getPort(Hello2ImpPort, IHello.class, features);
    }

}
