package com.oo.spring.WS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.7
 * 2013-05-09T17:47:34.751+08:00
 * Generated source version: 2.6.7
 * 
 */
@WebService(targetNamespace = "http://com.test", name = "IHello")
@XmlSeeAlso({ObjectFactory.class})
public interface IHello {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geetList", targetNamespace = "http://com.test", className = "com.oo.spring.WS.GeetList")
    @WebMethod
    @ResponseWrapper(localName = "geetListResponse", targetNamespace = "http://com.test", className = "com.oo.spring.WS.GeetListResponse")
    public java.lang.String geetList(
        @WebParam(name = "list", targetNamespace = "")
        java.util.List<java.lang.String> list
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geetHell", targetNamespace = "http://com.test", className = "com.oo.spring.WS.GeetHell")
    @WebMethod
    @ResponseWrapper(localName = "geetHellResponse", targetNamespace = "http://com.test", className = "com.oo.spring.WS.GeetHellResponse")
    public java.lang.String geetHell(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
